Adding Basic Logging
facebookincubator/CP4M pull request #2
Opened 2023-08-18 16:49 UTC by colinmccloskey

Added error and above logs to a local log file for now, but can stick with just standard out for now too

Also added main (for testing) and logs to git ignore

2023-08-18 20:04 UTC, hunterjackson requested changes
Lets also add an alternative log file for testing that logs to the console only

2023-08-18 20:04 UTC, hunterjackson commented on src/main/resources/log4j2.xml
> +<Configuration status="WARN" monitorInterval="30">
Does this clean up it's own logs? I don't see any log rotating/deleting.

2023-08-18 20:04 UTC, hunterjackson commented on .gitignore
> +src/main/java/com/meta/chatbridge/Main.java
we're going to need this file to be included very soon :)

2023-08-18 20:04 UTC, hunterjackson commented on pom.xml
> +<!--        </dependency>-->
Do we not need this? If not lets delete

2023-08-18 20:04 UTC, hunterjackson commented on .idea/encodings.xml
> -    <file url="file://$PROJECT_DIR$/src/main/resources" charset="UTF-8" />
?

2023-08-18 20:08 UTC, hunterjackson commented on src/main/resources/log4j2.xml
> +        <File name="file" fileName="logs/app.log">
anyway to set this dynamically or some an env variable or something? lets also pick a default location that isn't relative and makes sense, maybe `/var/log/cp4m`

2023-08-18 20:09 UTC, hunterjackson commented on src/main/resources/log4j2.xml
> +        <File name="file" fileName="logs/app.log">
also if the the sub-directories don't exist does this create them?

2023-08-19 05:37 UTC, colinmccloskey commented on .idea/encodings.xml
> -    <file url="file://$PROJECT_DIR$/src/main/resources" charset="UTF-8" />
This kept auto-deleting, not sure why

2023-08-19 05:39 UTC, colinmccloskey commented
Just removing file logging for now - will add in a second commit with a RollingFileAppender with deletion to keep tracks of logs by date and delete old ones

2023-08-22 20:25 UTC, merged